inputSpec: ./api.v0.yaml
outputDir: .
generatorName: typescript-axios
gitUserId: curvegrid
gitRepoId: multibaas-sdk-typescript
licenseName: MIT
additionalProperties:
  npmName: "@curvegrid/multibaas-sdk"
  npmVersion: 1.1.0
  disallowAdditionalPropertiesIfNotPresent: true
  legacyDiscriminatorBehavior: false
  withInterfaces: true
  supportsES6: true
